# Generated by Django 3.0.7 on 2020-09-10 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_addr', models.GenericIPAddressField(null=True)),
                ('network_prefix', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)])),
                ('network_interface_name', models.CharField(max_length=200, null=True)),
                ('version', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='RipAdvanced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbor', models.GenericIPAddressField(null=True)),
                ('passive_interface', models.CharField(max_length=200, null=True)),
                ('allow_ecmp', models.BooleanField(null=True)),
                ('default_info_originate', models.BooleanField(null=True)),
                ('redistribute', models.CharField(choices=[('connected', 'connected'), ('bgp', 'bgp'), ('static', 'static'), ('ospf', 'ospf')], max_length=200, null=True)),
                ('default_metric', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('distance', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('distribute_list_perfix_in_out', models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=200, null=True)),
                ('timers_update_time', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(2147483647)])),
                ('timers_time_out', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(2147483647)])),
                ('timers_garbage_time', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(2147483647)])),
                ('interface_name', models.CharField(max_length=200, null=True)),
                ('interface_auth_key_chain', models.CharField(max_length=200, null=True)),
                ('interface_auth_string', models.CharField(max_length=200, null=True)),
                ('interface_auth_mode_md5', models.BooleanField(null=True)),
                ('interface_auth_mode_text', models.BooleanField(null=True)),
                ('interface_receive_version', models.CharField(choices=[('1', '1'), ('2', '2'), ('none', 'none')], max_length=200, null=True)),
                ('interface_send_version', models.CharField(choices=[('1', '1'), ('2', '2'), ('none', 'none')], max_length=200, null=True)),
            ],
        ),
    ]
