# Generated by Django 3.0.7 on 2020-09-10 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_dst', models.GenericIPAddressField(null=True)),
                ('ip_dst_prefix', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)])),
                ('gateway', models.GenericIPAddressField(null=True)),
                ('interface_gateway', models.CharField(max_length=200, null=True)),
                ('null_interface', models.BooleanField(null=True)),
                ('distance', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('reject', models.BooleanField(null=True)),
            ],
        ),
    ]
