# Generated by Django 3.0.7 on 2020-09-19 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bgp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4294967295)])),
                ('router_id', models.GenericIPAddressField(null=True)),
                ('neighbor_addr', models.GenericIPAddressField(null=True)),
                ('neighbor_interface_name', models.CharField(max_length=200, null=True)),
                ('remote_as_num', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4294967295)])),
                ('remote_as_internal', models.BooleanField(null=True)),
                ('remote_as_external', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BgpAddrFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4294967295)])),
                ('type_addr_family', models.CharField(choices=[('unicast', 'unicast'), ('multicast', 'multicast'), ('none', 'none')], max_length=200, null=True)),
                ('aggregate_address', models.GenericIPAddressField(null=True)),
                ('aggregate_address_prefix', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32)])),
                ('aggregate_address_as_set', models.BooleanField(null=True)),
                ('aggregate_address_routemap', models.CharField(max_length=200, null=True)),
                ('aggregate_address_summery_only', models.BooleanField(null=True)),
                ('distance_admin', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('distance_admin_ip', models.GenericIPAddressField(null=True)),
                ('distance_admin_prefix', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32)])),
                ('distance_external_routes', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('distance_internal_routes', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('distance_local_routes', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('maximum_paths', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(64)])),
                ('maximum_paths_ibgp', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(64)])),
                ('network_addr', models.GenericIPAddressField(null=True)),
                ('network_addr_prefix', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32)])),
                ('network_route_map', models.CharField(max_length=200, null=True)),
                ('redistribute', models.CharField(choices=[('connected', 'connected'), ('ospf', 'ospf'), ('static', 'static'), ('rip', 'rip')], max_length=200, null=True)),
                ('neighbor_addr', models.GenericIPAddressField(null=True)),
                ('neighbor_interface_name', models.CharField(max_length=200, null=True)),
                ('neighbor_addpath_tx_all_paths', models.BooleanField(null=True)),
                ('neighbor_addpath_tx_bestpath_per_as', models.BooleanField(null=True)),
                ('neighbor_allowas_in', models.BooleanField(null=True)),
                ('neighbor_allowas_in_origin', models.BooleanField(null=True)),
                ('neighbor_as_override', models.BooleanField(null=True)),
                ('neighbor_attribute_unchanged_all', models.BooleanField(null=True)),
                ('neighbor_attribute_unchanged_as_path', models.BooleanField(null=True)),
                ('neighbor_attribute_unchanged_med', models.BooleanField(null=True)),
                ('neighbor_attribute_unchanged_nexthop', models.BooleanField(null=True)),
                ('neighbor_default_originate', models.BooleanField(null=True)),
                ('neighbor_default_originate_routemap', models.CharField(max_length=200, null=True)),
                ('neighbor_distribute_list_num', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(199)])),
                ('neighbor_distribute_list_expanded', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(2699)])),
                ('neighbor_distribute_list_in_out', models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=200, null=True)),
                ('neighbor_prefix_list', models.CharField(max_length=200, null=True)),
                ('neighbor_prefix_list_in_out', models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=200, null=True)),
                ('neighbor_route_map', models.CharField(max_length=200, null=True)),
                ('neighbor_route_map_in_out', models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=200, null=True)),
                ('neighbor_send_community', models.CharField(choices=[('all', 'all'), ('both', 'both'), ('extended', 'extended'), ('large', 'large'), ('standard', 'standard'), ('none', 'none')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BgpGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4294967295)])),
                ('neighbor_addr', models.GenericIPAddressField(null=True)),
                ('neighbor_interface_name', models.CharField(max_length=200, null=True)),
                ('neighbor_update_source_addr', models.GenericIPAddressField(null=True)),
                ('neighbor_update_source_interface_name', models.CharField(max_length=200, null=True)),
                ('neighbor_ebgp_multihop', models.BooleanField(null=True)),
                ('neighbor_ebgp_multihop_numhop', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('neighbor_shutdown', models.BooleanField(null=True)),
                ('neighbor_keepalive', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('neighbor_holdtime', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('neighbor_connect_timer', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('neighbor_password', models.CharField(max_length=200, null=True)),
                ('neighbor_passive', models.BooleanField(null=True)),
                ('neighbor_ttl_security', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('timer_keepalive', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('timer_holdtime', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('update_delay', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3600)])),
            ],
        ),
    ]
